#
# This is a docker-compose file starts and runs
# This uses 4 images/services
# Stedi
# Redis
# Zookeeper 
# Kafka
#

version 3.7

services
	zookeeper:
		image:
		ports:
		
		environment:
			ZOOKEEPER_CLIENT_PORT: ""

	kafka:
		image:
		ports:
		
		environment:
			KAFKA_BROKER_ID: 
      			KAFKA_ZOOKEEPER_CONNECT: ""
      			KAFKA_ADVERTISED_LISTENERS: ""
      			KAFKA_INTER_BROKER_LISTENER_NAME: ""
      			KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ""
      			KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ""
    		depends_on:
    		- "zookeeper"

	redis:
		image:
		ports:

		environment:

	stedi:
		image:
		ports:
		
		environment:

		depends_on:
		- "kafka"
		- "redis"